apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: check-traces
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: check-traces
    app.kubernetes.io/part-of: check-traces
  name: check-traces
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: check-traces
status:
  loadBalancer: {}
